"""Pydantic schemas — re-export all public DTOs."""

from app.schemas.dto import (
    # Shared
    ScalesModel,
    PaginatedResponse,
    ProblemDetail,
    HealthCheck,
    # Venues
    VenueAddress,
    VenueContact,
    VenueBranding,
    VenueSettings,
    VenueOperatingHours,
    VenueBase,
    VenueCreate,
    VenueUpdate,
    VenueOut,
    VenueCompactOut,
    VenueStats,
    # Onboarding / billing / admin
    VenueSignupRequest,
    VenueSignupResponse,
    VenueBillingOut,
    CheckoutSessionRequest,
    CheckoutSessionOut,
    SubscriptionStatusOut,
    WebhookEventOut,
    BillingPortalRequest,
    BillingPortalOut,
    AdminVenueOut,
    AdminVenueListItem,
    AdminVenueStatusUpdate,
    AdminVenueProvisionRequest,
    AdminDashboardOut,
    AdminVenuePurgeResult,
    AdminVenueRestore,
    AdminAuditLogOut,
    AdminBillingMetricsOut,
    # Accounts (global mobile identity)
    AccountRegisterRequest,
    AccountLoginRequest,
    AccountMeOut,
    AccountMeUpdate,
    TokenPairOut,
    AccountRegisterResponse,
    # Songs
    SongBase,
    SongCreate,
    SongUpdate,
    SongOut,
    SongSearchQuery,
    SongListParams,
    # Singers
    SingerBase,
    SingerCreate,
    SingerUpdate,
    SingerOut,
    CheckInSessionOut,
    CheckInRequest,
    CheckInResponse,
    # Queue
    QueueRequestBase,
    QueueRequestCreate,
    QueueRequestOut,
    QueueAction,
    QueueReorder,
    QueueRejectRequest,
    QueueRequestUpdate,
    QueueItemOut,
    QueueAdminListOut,
    QueueReorderBySinger,
    QueueSkipToEnd,
    RotationModeSet,
    QueueAnalyticsOut,
    BanRequest,
    BanResponse,
    # Loyalty
    LoyaltyTierOut,
    LoyaltyTierCreate,
    LoyaltySummary,
    LoyaltyPointsTransaction,
    QuestCreate,
    QuestOut,
    RewardOut,
    ManualAwardRequest,
    # Commerce
    ProductBase,
    ProductCreate,
    ProductOut,
    CartItemCreate,
    CartOut,
    CheckoutRequest,
    CheckoutResponse,
    OrderOut,
    # Analytics
    AnalyticsSummary,
    TimeRangeQuery,
    VenueOverviewOut,
    SingerLeaderboardEntry,
    SongPopularityEntry,
    HourlyBreakdownItem,
    SingerStatsOut,
    # Social
    LeaderboardEntryOut,
    ConsentSettings,
    ShareRequest,
    ShareResponse,
    # Points & Achievements
    PointsLedgerOut,
    AchievementOut,
    LeaderboardPeriodQuery,
    # Singer Portal
    SingerHistoryItem,
    SingerHistoryOut,
    SingerPortalStats,
    SingerProfileStats,
    SingerQueueItem,
    SingerQueueOut,
    SingerQueueHistoryItem,
    SingerQueueHistoryOut,
    SingerQueueStatus,
    SingerMeUpdate,
    # Payments
    PaymentCreate,
    TipRequest,
    PriorityBumpRequest,
    PaymentIntentOut,
    PaymentOut,
    PaymentHistoryOut,
    RefundRequest,
    RefundOut,
    WebhookSimulationRequest,
    # Sync
    # Sync / link
    SyncQueuePushPayload,
    SyncQueuePullOut,
    SyncQueueItem,
    SyncSingersPushPayload,
    SyncSingersPullOut,
    SyncSingerItem,
    SyncSongsPushPayload,
    SyncSongsPullOut,
    SyncSongItem,
    SyncSongPullItem,
    SyncSongsScanPayload,
    SyncSongsAvailabilityBatch,
    SyncSettingsPushPayload,
    SyncSettingsPullOut,
    SyncSettingItem,
    SyncConflictResponse,
    SyncConflictDetail,
    SingerLinkRequest,
    SingerLinkMergeOut,
    SingerMergeRequest,
    # Full Repair Sync
    RepairSyncMode,
    RepairSyncStatus,
    RepairSyncConflict,
    RepairSyncConflictResolution,
    RepairSyncConflictFieldResolution,
    RepairSyncProgress,
    RepairSyncSummary,
    NowPlayingSnapshot,
    RepairSyncSingerSnapshot,
    RepairSyncQueueSnapshot,
    RepairSyncSettingsSnapshot,
    RepairSyncSnapshot,
    RepairSyncStartRequest,
    RepairSyncResolveRequest,
    RepairSyncOut,
    RepairSyncJobSummary,
    # Notifications
    DeviceTokenBase,
    DeviceTokenCreate,
    DeviceTokenOut,
    NotificationOut,
    NotificationListOut,
    NotificationMarkReadRequest,
    NotificationMarkReadResponse,
    NotificationSettingsOut,
    NotificationSettingsUpdate,
    # GDPR / Data Privacy
    DataExportOut,
    GDPRDeleteResponse,
)


from app.schemas.favorites import FavoriteBase, FavoriteCreate, FavoriteOut
from app.schemas.social import FollowCreate, FollowOut, FollowStatusOut
from app.schemas.queue import (
    QueueJoinRequest,
    QueueJoinResponse,
    QueueStatusResponse,
    QueueLeaveAllResponse,
    PublicQueueItem,
    PublicQueueOut,
)
