"""Pydantic schemas — re-export all public DTOs."""

from app.schemas.dto import (
    # Shared
    ScalesModel,
    PaginatedResponse,
    ProblemDetail,
    HealthCheck,
    # Venues
    VenueAddress,
    VenueContact,
    VenueBranding,
    VenueSettings,
    VenueOperatingHours,
    VenueBase,
    VenueCreate,
    VenueUpdate,
    VenueOut,
    VenueCompactOut,
    VenueStats,
    # Songs
    SongBase,
    SongCreate,
    SongUpdate,
    SongOut,
    SongSearchQuery,
    SongListParams,
    # Singers
    SingerBase,
    SingerCreate,
    SingerUpdate,
    SingerOut,
    CheckInSessionOut,
    CheckInRequest,
    CheckInResponse,
    CheckInSessionOut,
    # Queue
    QueueRequestBase,
    QueueRequestCreate,
    QueueRequestOut,
    QueueAction,
    QueueReorder,
    QueueRejectRequest,
    QueueRequestUpdate,
    QueueItemOut,
    QueueAdminListOut,
    # Loyalty
    LoyaltyTierOut,
    LoyaltyTierCreate,
    LoyaltySummary,
    LoyaltyPointsTransaction,
    QuestCreate,
    QuestOut,
    RewardOut,
    ManualAwardRequest,
    # Commerce
    ProductBase,
    ProductCreate,
    ProductOut,
    CartItemCreate,
    CartOut,
    CheckoutRequest,
    CheckoutResponse,
    OrderOut,
    # Analytics
    AnalyticsSummary,
    TimeRangeQuery,
    VenueOverviewOut,
    SingerLeaderboardEntry,
    SongPopularityEntry,
    HourlyBreakdownItem,
    SingerStatsOut,
    # Social
    LeaderboardEntryOut,
    ConsentSettings,
    ShareRequest,
    ShareResponse,
    # Singer Portal
    SingerHistoryItem,
    SingerHistoryOut,
    SingerPortalStats,
    # Sync
    SyncQueueItem,
    SyncQueuePushPayload,
    SyncQueuePullOut,
    SyncSingerItem,
    SyncSingersPushPayload,
    SyncSingersPullOut,
    SyncSongItem,
    SyncSongsPushPayload,
    SyncSongsPullOut,
    SyncSettingItem,
    SyncSettingsPushPayload,
    SyncSettingsPullOut,
    SyncConflictDetail,
    SyncConflictResponse,
)

from app.schemas.favorites import FavoriteBase, FavoriteCreate, FavoriteOut
from app.schemas.social import FollowCreate, FollowOut, FollowStatusOut
